#!/usr/bin/env node

var fs = require('fs');
var path = require('path');

var zipfile = path.resolve(__dirname, '../ES6.sublime-package');

try {
  fs.unlinkSync(zipfile);
  console.log('remove', zipfile);
} catch(e){
  console.log('not found', zipfile);
}