#!/usr/bin/env node

var Just = require('just-zip');
var fs = require('fs');
var path = require('path');

var zipfile = path.resolve(__dirname, '../ES6.zip');

try {
  fs.unlinkSync(zipfile);
} catch(e){}


console.log(zipfile);

Just(__dirname + '/', path.resolve(__dirname, '../'), function(err, zip){
  if (err) {
    console.error('error', err);
  }
  else {
    console.log('save', zip);
    fs.renameSync(zip, zipfile);
  }
});
